<a href="https://colab.research.google.com/github/konradbachusz/Foundations_of_PyTorch_Pluralsight/blob/master/Foundations_of_PyTorch_Pluralsight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch torchvision

# Tensors

In [3]:
import torch
print(torch.__version__)

1.4.0


In [4]:
torch.get_default_dtype()

torch.float32

In [5]:
torch.set_default_dtype(torch.float64)
torch.get_default_dtype()

torch.float64

In [6]:
tensor_arr=torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [7]:
torch.numel(tensor_arr)

6

In [10]:
tensor_uninitialized=torch.Tensor(2,2)
tensor_uninitialized

tensor([[2.8562e-316, 1.5810e-322],
        [2.1220e-314, 1.5600e+161]])

In [11]:
tensor_initialized=torch.rand(2,2)
tensor_initialized

tensor([[0.3129, 0.2977],
        [0.4668, 0.1985]])

In [12]:
tensor_int=torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [13]:
tensor_short=torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [14]:
tensor_float=torch.tensor([1.0,2.0,3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [15]:
tensor_fill=torch.full((2,6),fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [16]:
tensor_of_ones=torch.ones([2,4],dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [17]:
tensor_of_zeros=torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [18]:
tensor_eye=torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
non_zero=torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [0]:
i=torch.tensor([[0,1,1],
                [2,2,0]])

In [0]:
v=torch.tensor([3,4,5],dtype=torch.float32)

In [0]:
sparse_tensor=torch.sparse_coo_tensor(i,v,[2,5])

In [24]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [25]:
initial_tensor=torch.rand(2,3)
initial_tensor

tensor([[0.4199, 0.4901, 0.6956],
        [0.9157, 0.7159, 0.8671]])

In [26]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [27]:
new_tensor=initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [28]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [30]:
x=torch.linspace(start=0.1,end=10.0,steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [31]:
tensor_chunk=torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [34]:
tensor1=tensor_chunk[0]
tensor2=tensor_chunk[1]
tensor3=torch.tensor([3.0,4.0,5.0])

torch.cat((tensor1,tensor2,tensor3),0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [36]:
random_tensor=torch.Tensor([[10,8,30],[40,5,6],[12,2,21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [37]:
random_tensor[0,1]

tensor(8.)

In [38]:
random_tensor.size()

torch.Size([3, 3])

In [39]:
resized_tensor=random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [40]:
random_tensor[2,2]=100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [41]:
 random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [43]:
tensor_unsqueeze=torch.unsqueeze(random_tensor,2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [44]:
initial_tensor.T

tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])

In [45]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [0]:
sorted_tensor,sorted_indicies=torch.sort(random_tensor)

In [47]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [48]:
sorted_indicies

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [50]:
tensor_float=torch.FloatTensor([-1.1,-2.2,3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [51]:
tensor_abs=torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [0]:
tensor=torch.Tensor([[-1,-2,-3],
                     [1,2,3]])

In [53]:
tensor_div=torch.div(tensor,tensor+3)
tensor_div

tensor([[-0.5000, -2.0000,    -inf],
        [ 0.2500,  0.4000,  0.5000]])

In [54]:
#element wise multiplication
tensor_mul=torch.mul(tensor,tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [55]:
#clamp within minumum and maximum range
tensor_clamp=torch.clamp(tensor,min=-0.2,max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

In [57]:
torch.argmax(tensor_abs)

tensor(2)

# Numpy to tensors

In [0]:
import numpy as np
import torch

In [59]:
tensor=torch.rand(4,3)
tensor

tensor([[0.2278, 0.6856, 0.0524],
        [0.1671, 0.6009, 0.6298],
        [0.7058, 0.9801, 0.1658],
        [0.6399, 0.8259, 0.9676]])

In [60]:
numpy_from_tensor=tensor.numpy()
numpy_from_tensor

array([[0.22781905, 0.68559668, 0.05238935],
       [0.16705729, 0.60085288, 0.62982138],
       [0.70577774, 0.98007033, 0.16581829],
       [0.63985291, 0.82592868, 0.96762898]])